[firstbit]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
  <meta name="generator" content="jemdoc, see http://jemdoc.jaboc.net/" />
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

  [defaultcss]
  <link rel="stylesheet" href="jemdoc.css" type="text/css" />

  [windowtitle]
# used in header for window title.
  <title>|</title>

  [fwtitlestart]
  <div id="fwtitle">

  [fwtitleend]
  </div>

  [doctitle]
# used at top of document.
  <div id="toptitle">
  <h1>|</h1>

  [subtitle]
  <div id="subtitle">|</div>

  [doctitleend]
  </div>

  [bodystart]
  </head>
  <body>

  [menustart]
  <table summary="Table for page layout." id="tlayout">
  <tr valign="top">
  <td id="layout-menu">

  [menuend]
  </td>
  <td id="layout-content">

  [menucategory]
  <div class="menu-category">|</div>

  [menuitem]
  <div class="menu-item"><a href="|1">|2</a></div>

  [specificcss]
  <link rel="stylesheet" href="|" type="text/css" />

  [currentmenuitem]
  <div class="menu-item"><a href="|1" class="current">|2</a></div>

  [nomenu]
  <div id="layout-content">

  [menulastbit]
  </td>
  </tr>
  </table>

  [nomenulastbit]
  </div>

  [bodyend]
  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-102057125-1']);
  _gaq.push(['_trackPageview']);
  (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
   })();
  </script>


  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-Z9033S0B09"></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-Z9033S0B09');
  </script>
  <!-- End Google tab -->

  <!-- MathJax --> 
  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script>
  <script type="text/x-mathjax-config">
  MathJax.Hub.Config({
	      TeX: { equationNumbers: { autoNumber: "AMS" } } 
  });
  </script>
  <!-- End MathJax --> 

  </body>
  </html>

  [infoblock]
  <div class="infoblock">

  [codeblock]
  <div class="codeblock">

  [blocktitle]
  <div class="blocktitle">|</div>

  [infoblockcontent]
  <div class="blockcontent">

  [codeblockcontent]
  <div class="blockcontent"><pre>

  [codeblockend]
  </pre></div></div>

  [codeblockcontenttt]
  <div class="blockcontent"><tt class="tthl">

  [codeblockendtt]
  </tt></div></div>

  [infoblockend]
  </div></div>

  [footerstart]
  <div id="footer">
  <div id="footer-text">

  [footerend]
  </div>
  </div>

  [lastupdated]
  Page generated |
  by <a href="https://github.com/jem/jemdoc">jemdoc</a>.

  [sourcelink]
  (<a href="|">source</a>)
